Create funnelback template
university-of-york/uoy-config-funnelback-courses pull request #2
Opened 2020-08-14 14:32 UTC by RichardAllum

2020-08-24 09:41 UTC, ncn1 commented on course-search.ftl
> +    </@s.InitialFormOnly>
```suggestion
```

2020-08-24 09:49 UTC, ncn1 commented on course-search.ftl
> +    <@s.AfterSearchOnly>
```suggestion
    <@s.AfterSearchOnly>
    <#-- ie. conditional display, content is evaluated only when there are results. -->
```

2020-08-24 10:22 UTC, ncn1 commented on course-search.ftl
> +                    "title": "${s.result.metadata.courseTitle}",
```suggestion
                    "title": "${s.result.metaData.courseTitle}",
```

2020-08-24 10:42 UTC, ncn1 commented on course-search.ftl
> +                <#if s.result.class.simpleName == "TierBar">
'Results are grouped by tier bars depending of how they match the query terms. There is usually one tier bar for the fully matching results and another one for the partially matching results.'
Quote from https://docs.funnelback.com/modernui-datamodel/com/funnelback/publicui/search/model/padre/TierBar.html
It is necessary, as removing it causes an error.

2020-08-24 11:08 UTC, ncn1 commented on course-search.ftl
> +                    <#else></#if>
```suggestion
```

2020-08-24 11:33 UTC, ncn1 commented on course-search.ftl
> +    <@fb.ViewModeBanner />
```suggestion
    <@fb.ViewModeBanner />
```

2020-08-25 09:39 UTC, FergusMcGlynn requested changes

2020-08-25 09:39 UTC, FergusMcGlynn commented on course-search.ftl
> +            <#if s.result.class.simpleName == "TierBar">
Could this be `if simpleName != "TierBar"` and then drop the `else`? Also I still don't really understand what "TierBar" means, so an inline comment might help to clarify?

2020-08-25 10:17 UTC, ncn1 approved these changes

2020-08-25 10:26 UTC, FergusMcGlynn approved these changes

2020-08-25 10:27 UTC, merged