Add README
university-of-york/uoy-config-funnelback-courses pull request #5
Opened 2020-08-24 10:50 UTC by RichardAllum

2020-08-24 10:53 UTC, mrgibbonsuoy commented on README.md
> +####To deploy a file:
Extra #

2020-08-24 10:54 UTC, mrgibbonsuoy approved these changes

2020-08-24 10:54 UTC, RichardAllum commented on README.md
> +####To deploy a file:
```suggestion
#### To deploy a file:
```

2020-08-24 11:24 UTC, ChristianBeddows commented on README.md
> +as the york-uni-web main York collection contains others.
york-uni-web is actually a plain web collection, whereas the Campus map collection is a 'meta' collection containing others

```suggestion
as the york-uni-campusmap collection contains others.
```

2020-08-24 11:34 UTC, ChristianBeddows commented on README.md
> +
Re-written part of this section to talk about uploading & archiving files
```suggestion
The simplest method of uploading/updating a file is to use the file picker at the bottom of the section. 
There is also a drop-down menu that allows for the creation of new files that indicates the possible filenames that will be recognised by Funnelback.

When uploading a new version of an existing file, the old one will be archived with a date-time stamp within Funnelback.
This allows for a change to be quickly reverted by using the 'Restore' option on an archived version.

Funnelback also provides a visual interface for viewing/editing existing files. 
Click on the name of the file you want to edit in the preview section to open the editor. 
You will need to copy the code from the matching file in Source Control to overwrite the file, and then click **Save**.

Test that the file is working by running an example search, then when you are satisfied return to the config list and click **Publish** to publish that file to Live.
```

2020-08-24 11:37 UTC, ChristianBeddows requested changes
Still getting used to GH PRs but I think this is the correct way to say that you need to action my suggestions before merging? I'm otherwise happy to approve this

2020-08-24 13:18 UTC, ncn1 commented on README.md
> +The OpenAPI specification can be viewed at https://university-of-york.github.io/uoy-config-funnelback-courses. It is served
I get a 404 error on this URL

2020-08-24 14:08 UTC, RichardAllum commented on README.md
> +The OpenAPI specification can be viewed at https://university-of-york.github.io/uoy-config-funnelback-courses. It is served
That will be the case until the gh-pages branch is set up, the URL should be correct though

2020-08-24 17:50 UTC, mrgibbonsuoy commented on README.md
> +The OpenAPI specification can be viewed at https://university-of-york.github.io/uoy-config-funnelback-courses. It is served
That should be fixed now Nicola.

2020-08-25 11:06 UTC, ChristianBeddows approved these changes

2020-08-25 14:08 UTC, RichardAllum commented on README.md
> +* [OpenAPI Documentation](https://swagger.io/specification/)
```suggestion
* [OpenAPI Documentation](https://swagger.io/docs/specification/)
```
Easier to read and more clear

2020-08-26 13:32 UTC, FergusMcGlynn approved these changes

2020-08-26 16:51 UTC, ce666-york requested changes
This is great, there's lots of really useful information here! I've made a few suggestions but I think the level of detail already here is really good 🙂

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +This repo contains configuration for the University of York's course search powered by [Funnelback](https://www.funnelback.com/).
Could we expand on this a little? e.g. `This configures a collection of course information within Funnelback, and a JSON API to search this collection. This can be seen at <sample search url>.`

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +as the york-uni-campusmap collection contains others.
Going to suggest we be consistent with formatting of collection names across this document

```suggestion
as the `york-uni-campusmap` collection contains others.
```

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +The course collection is called *york-uni-courses*.
```suggestion
The course collection is called `york-uni-courses`.
```

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +The York-uni-courses collection has two profiles, for 'Live' and 'Preview'. The preview profile can be used for testing
```suggestion
The `york-uni-courses` collection has two profiles, for 'Live' and 'Preview'. The preview profile can be used for testing 
```

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +The York-uni-courses collection has two profiles, for 'Live' and 'Preview'. The preview profile can be used for testing
Can we link to searches using the live and preview templates?

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +## OpenAPI Specification
I think this section should be further up, possibly above the Funnelback section. This is the interface that we're publishing, the output of this repo, and the Funnelback information is everything that goes behind it, so it makes sense that this would be first to me.

If we also mention the API and sample URL in the introduction then I think it ties nicely together at that point - that's just my feeling trying to think of someone coming to this for the first time!

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +## The Swagger UI
This is all really useful info, I wonder if it might be more suited to the main wiki? It's almost metadata about the repo i.e. how we set up the documentation, and how others could do it in future in their repos, rather than directly related to Funnelback config. Don't know if anyone else has thoughts on this?

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +The swagger UI allows the openAPI demonstration rendering of a Funnelback search return to be viewed in a way that users will find helpful.
```suggestion
The Swagger UI allows the OpenAPI demonstration rendering of a Funnelback search return to be viewed in a way that users will find helpful.
```

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +here as a static site using a distribution of [Swagger-UI](https://github.com/swagger-api/swagger-ui/tree/master/dist).
Better to have descriptive links (as you've done elsewhere!)

```suggestion
The [latest version of the API specification](https://university-of-york.github.io/uoy-config-funnelback-courses) is published and kept up-to-date automatically. 

It is defined using the [OpenAPI specification](https://swagger.io/docs/specification/about/) and is served as a static site using a distribution of [Swagger-UI](https://github.com/swagger-api/swagger-ui/tree/master/dist).
```

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +## OpenAPI Specification
Small suggestion, in case people don't know what OpenAPI specification is/means - we can explain that in the text.

```suggestion
## API Specification
```

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +Deployment of configuration files to Funnelback cannot be done programmatically, and must be done using the web interface.
Suggest we have a link to the Funnelback web interface

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +There is also a drop-down menu that allows for the creation of new files that indicates the possible filenames that will be recognised by Funnelback.
A screenshot is worth a thousand words 🙂 I could see it being really helpful e.g. if I needed to do an emergency deployment and hadn't really used Funnelback before

2020-08-26 16:51 UTC, ce666-york commented on README.md
> +The team have chosen to use github pages as the way to host the Swagger UI, the output is available at: https://university-of-york.github.io/uoy-config-funnelback-courses/  This is a publicly accessi
Suggest we add a Contact section at the bottom - using email addresses as this is a public repo.

```suggestion
The team have chosen to use github pages as the way to host the Swagger UI, the output is available at: https://university-of-york.github.io/uoy-config-funnelback-courses/  This is a publicly accessible location. 

## Contact

- [Digital Platforms and Developments Team](mailto:marketing-support@york.ac.uk)
- [Enterprise Systems Teaching and Learning Team](mailto:esg-teaching-and-learning-group@york.ac.uk)
```

2020-08-27 09:28 UTC, RichardAllum commented on README.md
> +This repo contains configuration for the University of York's course search powered by [Funnelback](https://www.funnelback.com/).
```suggestion
This repo contains configuration for the University of York's course search powered by [Funnelback](https://www.funnelback.com/). This configures a collection of course information within funnelback, which can be queried as an API returning JSON. This can be seen [here](https://york.funnelback.co.uk/s/search.json?collection=york-uni-courses&query=History&profile=_default_preview&form=course-search)
```

2020-08-27 10:51 UTC, RichardAllum commented on README.md
> +The York-uni-courses collection has two profiles, for 'Live' and 'Preview'. The preview profile can be used for testing
Should we include multiple links to the search or emphasise use of Swagger-UI (whose URL will never change) to evaluate the search?

2020-08-27 11:02 UTC, RichardAllum commented on README.md
> +There is also a drop-down menu that allows for the creation of new files that indicates the possible filenames that will be recognised by Funnelback.
```suggestion
There is also a drop-down menu that allows for the creation of new files that indicates the possible filenames that will be recognised by Funnelback.
![File picker](https://user-images.githubusercontent.com/68321515/91434581-f0095480-e85c-11ea-9480-f95f217d6a46.png)
```

2020-08-27 13:13 UTC, RichardAllum commented on README.md
> +Deployment of configuration files to Funnelback cannot be done programmatically, and must be done using the web interface.
```suggestion
Deployment of configuration files to Funnelback cannot be done programmatically, and must be done using the [web interface](https://york.funnelback.co.uk/search/admin).
```

2020-08-28 11:41 UTC, ce666-york commented on README.md
> +This repo contains configuration for the University of York's course search powered by [Funnelback](https://www.funnelback.com/). This configures a collection of course information within funnelback,
```suggestion
This repo contains configuration for the University of York's course search powered by [Funnelback](https://www.funnelback.com/). This configures a collection of course information within Funnelback, which can be queried as an API returning JSON. This can be seen [here](https://york.funnelback.co.uk/s/search.json?collection=york-uni-courses&query=History&profile=_default_preview&form=course-search)
```

2020-08-28 13:08 UTC, ncn1 approved these changes

2020-09-01 12:47 UTC, ce666-york approved these changes

2020-09-01 12:47 UTC, merged